site:
  tab: 翗羽_Keyu
  title: Keyuの博客
  title_type: image
  description: 个人博客，记录和分析技术学习
  language: zh
  favicon: /favicon.ico
  theme:
    light: garden
    dark: dracula
    code: snazzy-light
  date_format: ddd MMM DD YYYY
  blog:
    pageSize: 8
  banner:
    enableRandom: false
    randomUrl: ''
    randomCount: 5
    height: 70vh
    images: []
  icp: 粤ICP备2026094428号
  icp_link: https://beian.miit.gov.cn/
  icp_icon: ri:government-line
  police: ''
  police_link: https://beian.mps.gov.cn/
  police_icon: mdi:shield-account-outline
  pages:
    home:
      title: 欢迎来到我的站点
      subtitle: 请填写首页横幅副标题
      typewriterTexts: []
    friend:
      title: 友情链接
      subtitle: 请添加你的友链
    about:
      title: 关于我
      subtitle: 请填写个人介绍
    navigation:
      title: 网站导航
      subtitle: 请添加常用网站
    anime:
      title: 追番
      subtitle: 配置后展示追番列表
    project:
      title: 项目
      subtitle: 请添加你的项目
    album:
      title: 相册
      subtitle: 请上传你的照片
    music:
      title: 音乐
      subtitle: 请添加你的歌单
  meting:
    server: netease
    id: ''
    br: '320'
    trans: false
  menu:
    - id: write
      text: 写作
      href: /write
      svg: material-symbols:edit-square-outline-rounded
      target: _self
    - id: navigation
      text: 导航
      href: /navigation
      svg: material-symbols:explore-outline
      target: _self
    - id: anime
      text: 追番
      href: /anime
      svg: material-symbols:movie-outline
      target: _self
    - id: album
      text: 相册
      href: /album
      svg: material-symbols:photo-library-outline-rounded
      target: _self
    - id: music
      text: 音乐
      href: /music
      svg: material-symbols:music-note-rounded
      target: _self
    - id: project
      text: 项目
      href: /project
      svg: material-symbols:code-blocks-outline
      target: _self
    - id: friend
      text: 友链
      href: /friend
      svg: material-symbols:supervisor-account-outline-rounded
      target: _self
anime:
  bilibili:
    uid: '238183001'
  tmdb:
    apiKey: ''
    listId: ''
music:
  playlists: []
github:
  owner: KeyuNeko
  repo: RyuChan
  branch: main
  appId: '4355661'
  encryptKey: >-
    MIIEowIBAAKCAQEArY5hzHNeVekZojaAEcehsM76toE6EhBNO0326LVckj6VwTKP
    1vc8SLrXQ2NLhqk89XW5kDuNEnAivhJg+HjeeSG6yOxA8/EVLhvKtm3FUw4mF3+T
    VvhNWgn6ZgEBzNK/M9FZs0Xd69RTa3bXeQfadpVcSycqLsTwfL9+gcCHQO8ZWX4i
    ZyQRhymwO28X8KX50JlgoXm7WClVZ6u8sp3bREddZF78JaxVGNbiKN59tk8E9CGK
    IOwzsm3+pLiDIbOOnHbbqNA9jd+VuXKn9ewtUlUPqX2eXY8+MZBaBb6lAC5FaO1G
    o7wFY8FPDEgUT02HwKNtUlS7g8D3aL5c1cVskQIDAQABAoIBAC71+MZ+bQcn9JSs
    1Ih7EOgriTE61ECxAoTKesXK1QqJPrIxATS0Xy56x+ZnBregMWtleFlrk6dqiiwO
    AwkYg3IZS1Y0fvrCv+1i/b3RA/SOPoZbMb31n9B+JK/XE+qdF7loqzHT9NFr+Up5
    tKH+GwG9NmTrawGOrlfC5PMs6iwKVB5xOwYV4gPeVCJ+upDlGA5kN5LFQgaUysgl
    FYCbGd6nkcG8eGBaRgmVELYN1zdoIfPuJcQAYin5/RFzlu4ioEq5SmIOWt2q8BSI
    FlN5hr3rgLm5cWEdWYte+D/40ujRvgyCi9cH66yBsA9YCegtEa9Wp+46Dd+QSvNq
    GfSmyHUCgYEA2PfSCWF+lEyY5HwB+EyGw0aYoHKMzZHiXQdPFusb3wrex/yRfEME
    Ogt+nvW0AUBVL0UyuEbLL5TSwFmoEw7mTAF3vGCKBjRyVehFbi6t8dXgLs1V7ls6
    skHa5erjVnPm6woVOxYSR4WxgeUfuHAFIWP8WsNNhudxHHblRnTvlecCgYEAzMdI
    5hYExIiW1IrDruJVRyX4LRABWEJrCpxGVYSDqt1MVxRMrqloOBmkoGnqRPMP3AFr
    uj8YQDWCxebskoXHhdSePPzC7t0wtPJr0uWMEfJA9LTqIR/Xk3KCXmS5+ZhaQIpJ
    7bSAFSS8p3k9yxKIQP6nDd5bLi1wMyBRYVmQKscCgYBx+l4AR5MzXLnE7dArHCh/
    VQrA3uxQ4Z5EuJ43r/LITPGTpX7YBGyoAXnXD8QsFBur5XIrlCURLeE44uCEgoNA
    0lSQRTa847hcoNQ4eZUvQeevLndB6/L9ydKwjaA3vlNEjdtxWrrnj7gcQL1VKqPH
    UrszAv4rLFIjXeI8DRn/aQKBgQCbgmd425XJTlUEmVCbeaP7QPlj9zieNuolB6Je
    BSEcW6xCoNbO+TV9DPQ5IdXXgKI1mBqgOJQJBtoFwiU77D4mAt4cQHMkhHMdps99
    O/cQFeGAM/dtKkpC3f3lAyc8RZecVahozN9LrzdZEzh7A9rXSMvCO28Q9U60dMF4
    ZVSXNwKBgHhLxwA2HPU4jYp1OoTrOfA1Au+IeHYWBbWcVioLvNxCD13Cx1/+ZXWn
    718ZUYlFuU0z8DBS+gzvCXYPtrA/nRr76/XiRoTWqIog76jUeXY7WXAcj0ZvJSOk
    B7XRzknm79+axo29FpttK0XBpGnmvXP968MEaKikx6dd7aep28fm
umami:
  enable: false
  baseUrl: ''
  shareId: ''
  websiteId: ''
  timezone: Asia/Shanghai
user:
  name: 翗羽_Keyu
  description: ''
  site: https://ke.uy
  avatar: /profile.png
  title_image: /logo.png
  qr_wechat: ''
  qr_alipay: ''
  sidebar:
    social:
      - href: https://space.bilibili.com/238183001
        title: Bilibili
        ariaLabel: Bilibili
        svg: ri:bilibili-line
      - href: https://github.com/KeyuNeko
        title: Github
        ariaLabel: Github
        svg: ri:github-line
      - href: mailto:KeyuNeko@outlook.com
        title: Email
        ariaLabel: Email
        svg: ri:mail-line
  footer:
    social:
      - href: https://space.bilibili.com/238183001
        title: Bilibili
        ariaLabel: Bilibili
        svg: ri:bilibili-line
      - href: https://github.com/KeyuNeko
        title: Github
        ariaLabel: Github
        svg: ri:github-line
      - href: mailto:KeyuNeko@outlook.com
        title: Email
        ariaLabel: Email
        svg: ri:mail-line
comments:
  enable: false
  type: none
  giscus:
    repo: ''
    repoId: ''
    category: General
    categoryId: ''
    mapping: pathname
    lang: zh-CN
  waline:
    serverURL: ''
    lang: zh
  twikoo:
    envId: ''
